import nmap

def execute_basic_scan(target_ip: str):
    """
    Initializes Nmap and runs a basic service version scan (-sV) 
    against a few common ports to keep testing fast.
    """
    nm = nmap.PortScanner()
    
    # Arguments: 
    # -p 21,22,80 : Only scan FTP, SSH, and HTTP right now
    # -sV         : Probe open ports to determine service/version info
    scan_args = '-p 21,22,80 -sV'
    
    # Run the scan
    nm.scan(hosts=target_ip, arguments=scan_args)
    
    # Return the raw dictionary generated by python-nmap
    if target_ip in nm.all_hosts():
        return nm[target_ip]
    else:
        return {"error": "Host seems down or unreachable from container."}